// Generates src/schema.generated.js from migrations/*.sql so the site can
// apply its own database updates on deploy (see src/migrate.js).
// Run after adding or editing a migration:  npm run schema
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../migrations/', import.meta.url);
const files = readdirSync(dir).filter((f) => f.endsWith('.sql')).sort();

const migrations = files.map((file) => {
  const sql = readFileSync(new URL(file, dir), 'utf8')
    .split('\n').map((line) => line.replace(/--.*$/, '')).join('\n');
  const statements = sql.split(';').map((s) => s.replace(/\s+/g, ' ').trim()).filter(Boolean)
    // Every statement must be safe to re-run.
    .map((s) => s
      .replace(/^CREATE TABLE (?!IF NOT EXISTS)/i, 'CREATE TABLE IF NOT EXISTS ')
      .replace(/^CREATE (UNIQUE )?INDEX (?!IF NOT EXISTS)/i, 'CREATE $1INDEX IF NOT EXISTS '));
  return { id: file.replace(/\.sql$/, ''), statements };
});

writeFileSync(new URL('../src/schema.generated.js', import.meta.url),
  '// Generated by scripts/build-schema.mjs from migrations/*.sql. Do not edit by hand.\n' +
  `export const MIGRATIONS = ${JSON.stringify(migrations, null, 2)};\n`);
console.log(`Wrote ${migrations.length} migrations: ${migrations.map((m) => m.id).join(', ')}`);
